#!/bin/bash

cd target

if [ -d characters ]
then
    rm -f characters/*.properties
else
    mkdir characters
fi

if [ -d arenas ]
then
    rm -f arenas/*.properties
else
    mkdir arenas
fi

if [ -d scripts ]
then
    rm -f scripts/*.script
else
    mkdir scripts
fi

cp ../src/test/resources/char.*.properties characters
cp ../src/test/resources/arena.*.properties arenas
cp ../src/test/resources/*.script scripts

java -jar yafvt-0.0.1-SNAPSHOT.jar